services:
  arango:
    image: arangodb:3.11
    restart: unless-stopped
    environment:
      - ARANGO_ROOT_PASSWORD=
    volumes:
      - data:/var/lib/arangodb3
      - apps:/var/lib/arangodb3-apps
    ports:
      - 8529:8529
    
volumes:
  data:
  apps:
