name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: ArangoDB 3.7.1
      run: docker run -d --rm -e ARANGO_ROOT_PASSWORD= -p 8529:8529 arangodb:3.7.1
    
    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.401
        
    - name: Build Version
      id: vars
      run: echo "::set-output name=VERSION::<Version>${GITHUB_REF#refs/tags/}</Version>"
      
    - name: Apply Version
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "<Version>.*<\\/Version>"
        replace: "${{ steps.vars.outputs.VERSION }}"
        include: ".*\\.csproj"
    
    - name: Build
      run: dotnet build --configuration Release
      
    - name: Test
      run: dotnet test --configuration Release

    - name: Pack
      run: dotnet pack --configuration Release
      
    - name: Publish
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json